.TH vz 1 "Apr 2010" VZ "Manual"
.SH NAME
.PP
vz \- VZite Computation Server
.SH SYNOPSIS
.PP
.B vz
[\fIoptions\fP]
.SH DESCRIPTION
.PP
vz is a distributed computation server.
.SH OPTIONS
.PP
.IP "-q"
Quiet mode.
.IP "-v"
Increase verbosity.
.IP "-d"
Increase debugging.
.IP "-h"
Display help.
.SH FEATURES
.PP
The features are covered in the documentation.  See the README file.
.SH FILES
.PP
None.	
.SH COPYRIGHT
Copyright (c) 2010 John Plevyak, All Rights Reserved
.PP
VZite Home Page: http://vzite.com

